title:        k97Blog
tagline:      "Weblog of Karthikeyan"
description:  "The postings on this site are my own and does not necessarily represent my employer's positions, strategies or opinions."
url:          http://k97.in
version:      5.0.0
author:
  name:       'Karthikeyan'
  email:      'kingkarthik97@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     3
